name: Build docker image

on:
  push:
    tags:
      - '*'

  workflow_dispatch:


jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/remnawave-json
          flavor: latest=true
          tags: |
            type=sha
            type=raw,value=${{ github.ref_name }}
            type=ref,event=tag
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  create-release:
    needs: [build-docker-image]
    runs-on: ubuntu-latest
    steps:
      - name: NewTag
        id: tag
        uses: JinoArch/get-latest-tag@latest

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GH_DEPLOY }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: v${{ github.ref_name }}
          body: |
            🚀 Release v${{ github.ref_name }}

            📝 Compare changes: [${{ steps.tag.outputs.previousTag }}...${{ steps.tag.outputs.latestTag }}](https://github.com/${{ github.repository }}/compare/${{ steps.tag.outputs.previousTag }}...${{ steps.tag.outputs.latestTag }})

            Latest Docker image:
            - `ghcr.io/remnawave/backend:latest`

            Docker images:
            - `ghcr.io/${{ github.repository_owner }}/remnawave-json:${{github.ref_name}}`
          draft: false
          prerelease: false

